#
# Autogenerated by Frugal Compiler (3.4.10)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from .ttypes import *

const_i32_from_base = 582
