// Autogenerated by Frugal Compiler (2.22.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart' as thrift;
import 'package:variety/variety.dart' as t_variety;
import 'package:actual_base_dart/actual_base_dart.dart' as t_actual_base_dart;
import 'package:intermediate_include/intermediate_include.dart' as t_intermediate_include;
import 'package:validStructs/validStructs.dart' as t_validStructs;
import 'package:ValidTypes/ValidTypes.dart' as t_ValidTypes;
import 'package:subdir_include_ns/subdir_include_ns.dart' as t_subdir_include_ns;

class EventWrapper implements thrift.TBase {
  static final thrift.TStruct _STRUCT_DESC = new thrift.TStruct("EventWrapper");
  static final thrift.TField _ID_FIELD_DESC = new thrift.TField("ID", thrift.TType.I64, 1);
  static final thrift.TField _EV_FIELD_DESC = new thrift.TField("Ev", thrift.TType.STRUCT, 2);
  static final thrift.TField _EVENTS_FIELD_DESC = new thrift.TField("Events", thrift.TType.LIST, 3);
  static final thrift.TField _EVENTS2_FIELD_DESC = new thrift.TField("Events2", thrift.TType.SET, 4);
  static final thrift.TField _EVENT_MAP_FIELD_DESC = new thrift.TField("EventMap", thrift.TType.MAP, 5);
  static final thrift.TField _NUMS_FIELD_DESC = new thrift.TField("Nums", thrift.TType.LIST, 6);
  static final thrift.TField _ENUMS_FIELD_DESC = new thrift.TField("Enums", thrift.TType.LIST, 7);
  static final thrift.TField _A_BOOL_FIELD_FIELD_DESC = new thrift.TField("aBoolField", thrift.TType.BOOL, 8);
  static final thrift.TField _A_UNION_FIELD_DESC = new thrift.TField("a_union", thrift.TType.STRUCT, 9);
  static final thrift.TField _TYPEDEF_OF_TYPEDEF_FIELD_DESC = new thrift.TField("typedefOfTypedef", thrift.TType.STRING, 10);
  static final thrift.TField _DEPR_FIELD_DESC = new thrift.TField("depr", thrift.TType.BOOL, 11);
  static final thrift.TField _DEPR_BINARY_FIELD_DESC = new thrift.TField("deprBinary", thrift.TType.STRING, 12);
  static final thrift.TField _DEPR_LIST_FIELD_DESC = new thrift.TField("deprList", thrift.TType.LIST, 13);

  int iD;
  static const int ID = 1;
  t_variety.Event ev;
  static const int EV = 2;
  List<t_variety.Event> events;
  static const int EVENTS = 3;
  Set<t_variety.Event> events2;
  static const int EVENTS2 = 4;
  Map<int, t_variety.Event> eventMap;
  static const int EVENTMAP = 5;
  List<List<int>> nums;
  static const int NUMS = 6;
  List<int> enums;
  static const int ENUMS = 7;
  bool aBoolField = false;
  static const int ABOOLFIELD = 8;
  t_variety.TestingUnions a_union;
  static const int A_UNION = 9;
  String typedefOfTypedef;
  static const int TYPEDEFOFTYPEDEF = 10;
  /// This is a docstring comment for a deprecated field that has been spread
  /// across two lines.
  /// Deprecated: use something else
  @deprecated
  bool depr = false;
  static const int DEPR = 11;
  /// Deprecated: use something else
  @deprecated
  Uint8List deprBinary;
  static const int DEPRBINARY = 12;
  /// Deprecated: use something else
  @deprecated
  List<bool> deprList;
  static const int DEPRLIST = 13;


  EventWrapper() {
  }

  @deprecated
  bool isSetID() => ID != null;

  @deprecated
  unsetID() => ID = null;

  @deprecated
  bool isSetEv() => Ev != null;

  @deprecated
  unsetEv() => Ev = null;

  @deprecated
  bool isSetEvents() => Events != null;

  @deprecated
  unsetEvents() => Events = null;

  @deprecated
  bool isSetEvents2() => Events2 != null;

  @deprecated
  unsetEvents2() => Events2 = null;

  @deprecated
  bool isSetEventMap() => EventMap != null;

  @deprecated
  unsetEventMap() => EventMap = null;

  @deprecated
  bool isSetNums() => Nums != null;

  @deprecated
  unsetNums() => Nums = null;

  @deprecated
  bool isSetEnums() => Enums != null;

  @deprecated
  unsetEnums() => Enums = null;

  @deprecated
  bool isSetABoolField() => aBoolField != null;

  @deprecated
  unsetABoolField() => aBoolField = null;

  @deprecated
  bool isSetA_union() => a_union != null;

  @deprecated
  unsetA_union() => a_union = null;

  @deprecated
  bool isSetTypedefOfTypedef() => typedefOfTypedef != null;

  @deprecated
  unsetTypedefOfTypedef() => typedefOfTypedef = null;

  @deprecated
  bool isSetDepr() => depr != null;

  @deprecated
  unsetDepr() => depr = null;

  @deprecated
  bool isSetDeprBinary() => deprBinary != null;

  @deprecated
  unsetDeprBinary() => deprBinary = null;

  @deprecated
  bool isSetDeprList() => deprList != null;

  @deprecated
  unsetDeprList() => deprList = null;

  getFieldValue(int fieldID) {
    switch (fieldID) {
      case ID:
        return this.iD;
      case EV:
        return this.ev;
      case EVENTS:
        return this.events;
      case EVENTS2:
        return this.events2;
      case EVENTMAP:
        return this.eventMap;
      case NUMS:
        return this.nums;
      case ENUMS:
        return this.enums;
      case ABOOLFIELD:
        return this.aBoolField;
      case A_UNION:
        return this.a_union;
      case TYPEDEFOFTYPEDEF:
        return this.typedefOfTypedef;
      case DEPR:
        return this.depr;
      case DEPRBINARY:
        return this.deprBinary;
      case DEPRLIST:
        return this.deprList;
      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  setFieldValue(int fieldID, Object value) {
    switch(fieldID) {
      case ID:
        if (value == null) {
          iD = null;
        } else if (value is int) {
          iD = value;
        }

        break;

      case EV:
        if (value == null) {
          ev = null;
        } else if (value is t_variety.Event) {
          ev = value;
        }

        break;

      case EVENTS:
        if (value == null) {
          events = null;
        } else if (value is List<t_variety.Event>) {
          events = value;
        }

        break;

      case EVENTS2:
        if (value == null) {
          events2 = null;
        } else if (value is Set<t_variety.Event>) {
          events2 = value;
        }

        break;

      case EVENTMAP:
        if (value == null) {
          eventMap = null;
        } else if (value is Map<int, t_variety.Event>) {
          eventMap = value;
        }

        break;

      case NUMS:
        if (value == null) {
          nums = null;
        } else if (value is List<List<int>>) {
          nums = value;
        }

        break;

      case ENUMS:
        if (value == null) {
          enums = null;
        } else if (value is List<int>) {
          enums = value;
        }

        break;

      case ABOOLFIELD:
        if (value == null) {
          aBoolField = null;
        } else if (value is bool) {
          aBoolField = value;
        }

        break;

      case A_UNION:
        if (value == null) {
          a_union = null;
        } else if (value is t_variety.TestingUnions) {
          a_union = value;
        }

        break;

      case TYPEDEFOFTYPEDEF:
        if (value == null) {
          typedefOfTypedef = null;
        } else if (value is String) {
          typedefOfTypedef = value;
        }

        break;

      case DEPR:
        if (value == null) {
          depr = null;
        } else if (value is bool) {
          depr = value;
        }

        break;

      case DEPRBINARY:
        if (value == null) {
          deprBinary = null;
        } else if (value is Uint8List) {
          deprBinary = value;
        }

        break;

      case DEPRLIST:
        if (value == null) {
          deprList = null;
        } else if (value is List<bool>) {
          deprList = value;
        }

        break;

      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  // Returns true if the field corresponding to fieldID is set (has been assigned a value) and false otherwise
  bool isSet(int fieldID) {
    switch(fieldID) {
      case ID:
        return ID == null;

      case EV:
        return Ev == null;

      case EVENTS:
        return Events == null;

      case EVENTS2:
        return Events2 == null;

      case EVENTMAP:
        return EventMap == null;

      case NUMS:
        return Nums == null;

      case ENUMS:
        return Enums == null;

      case ABOOLFIELD:
        return aBoolField == null;

      case A_UNION:
        return a_union == null;

      case TYPEDEFOFTYPEDEF:
        return typedefOfTypedef == null;

      case DEPR:
        return depr == null;

      case DEPRBINARY:
        return deprBinary == null;

      case DEPRLIST:
        return deprList == null;

      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  read(thrift.TProtocol iprot) {
    thrift.TField field;
    iprot.readStructBegin();
    while(true) {
      field = iprot.readFieldBegin();
      if(field.type == thrift.TType.STOP) {
        break;
      }
      switch(field.id) {
        case ID:
          if(field.type == thrift.TType.I64) {
            iD = iprot.readI64();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EV:
          if(field.type == thrift.TType.STRUCT) {
            ev = new t_variety.Event();
            ev.read(iprot);
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTS:
          if(field.type == thrift.TType.LIST) {
            thrift.TList elem21 = iprot.readListBegin();
            events = new List<t_variety.Event>();
            for(int elem23 = 0; elem23 < elem21.length; ++elem23) {
              t_variety.Event elem22 = new t_variety.Event();
              elem22.read(iprot);
              events.add(elem22);
            }
            iprot.readListEnd();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTS2:
          if(field.type == thrift.TType.SET) {
            thrift.TSet elem24 = iprot.readSetBegin();
            events2 = new Set<t_variety.Event>();
            for(int elem26 = 0; elem26 < elem24.length; ++elem26) {
              t_variety.Event elem25 = new t_variety.Event();
              elem25.read(iprot);
              events2.add(elem25);
            }
            iprot.readSetEnd();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTMAP:
          if(field.type == thrift.TType.MAP) {
            thrift.TMap elem27 = iprot.readMapBegin();
            eventMap = new Map<int, t_variety.Event>();
            for(int elem29 = 0; elem29 < elem27.length; ++elem29) {
              int elem30 = iprot.readI64();
              t_variety.Event elem28 = new t_variety.Event();
              elem28.read(iprot);
              eventMap[elem30] = elem28;
            }
            iprot.readMapEnd();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case NUMS:
          if(field.type == thrift.TType.LIST) {
            thrift.TList elem31 = iprot.readListBegin();
            nums = new List<List<int>>();
            for(int elem36 = 0; elem36 < elem31.length; ++elem36) {
              thrift.TList elem33 = iprot.readListBegin();
              List<int> elem32 = new List<int>();
              for(int elem35 = 0; elem35 < elem33.length; ++elem35) {
                int elem34 = iprot.readI32();
                elem32.add(elem34);
              }
              iprot.readListEnd();
              nums.add(elem32);
            }
            iprot.readListEnd();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ENUMS:
          if(field.type == thrift.TType.LIST) {
            thrift.TList elem37 = iprot.readListBegin();
            enums = new List<int>();
            for(int elem39 = 0; elem39 < elem37.length; ++elem39) {
              int elem38 = iprot.readI32();
              enums.add(elem38);
            }
            iprot.readListEnd();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ABOOLFIELD:
          if(field.type == thrift.TType.BOOL) {
            aBoolField = iprot.readBool();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case A_UNION:
          if(field.type == thrift.TType.STRUCT) {
            a_union = new t_variety.TestingUnions();
            a_union.read(iprot);
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TYPEDEFOFTYPEDEF:
          if(field.type == thrift.TType.STRING) {
            typedefOfTypedef = iprot.readString();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DEPR:
          if(field.type == thrift.TType.BOOL) {
            depr = iprot.readBool();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DEPRBINARY:
          if(field.type == thrift.TType.STRING) {
            deprBinary = iprot.readBinary();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DEPRLIST:
          if(field.type == thrift.TType.LIST) {
            thrift.TList elem40 = iprot.readListBegin();
            deprList = new List<bool>();
            for(int elem42 = 0; elem42 < elem40.length; ++elem42) {
              bool elem41 = iprot.readBool();
              deprList.add(elem41);
            }
            iprot.readListEnd();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          thrift.TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    validate();
  }

  write(thrift.TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    if(ID != null) {
      oprot.writeFieldBegin(_ID_FIELD_DESC);
      oprot.writeI64(iD);
      oprot.writeFieldEnd();
    }
    if(this.ev != null) {
      oprot.writeFieldBegin(_EV_FIELD_DESC);
      ev.write(oprot);
      oprot.writeFieldEnd();
    }
    if(this.events != null) {
      oprot.writeFieldBegin(_EVENTS_FIELD_DESC);
      oprot.writeListBegin(new thrift.TList(thrift.TType.STRUCT, events.length));
      for(var elem43 in events) {
        elem43.write(oprot);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    if(this.events2 != null) {
      oprot.writeFieldBegin(_EVENTS2_FIELD_DESC);
      oprot.writeSetBegin(new thrift.TSet(thrift.TType.STRUCT, events2.length));
      for(var elem44 in events2) {
        elem44.write(oprot);
      }
      oprot.writeSetEnd();
      oprot.writeFieldEnd();
    }
    if(this.eventMap != null) {
      oprot.writeFieldBegin(_EVENT_MAP_FIELD_DESC);
      oprot.writeMapBegin(new thrift.TMap(thrift.TType.I64, thrift.TType.STRUCT, eventMap.length));
      for(var elem45 in eventMap.keys) {
        oprot.writeI64(elem45);
        eventMap[elem45].write(oprot);
      }
      oprot.writeMapEnd();
      oprot.writeFieldEnd();
    }
    if(this.nums != null) {
      oprot.writeFieldBegin(_NUMS_FIELD_DESC);
      oprot.writeListBegin(new thrift.TList(thrift.TType.LIST, nums.length));
      for(var elem46 in nums) {
        oprot.writeListBegin(new thrift.TList(thrift.TType.I32, elem46.length));
        for(var elem47 in elem46) {
          oprot.writeI32(elem47);
        }
        oprot.writeListEnd();
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    if(this.enums != null) {
      oprot.writeFieldBegin(_ENUMS_FIELD_DESC);
      oprot.writeListBegin(new thrift.TList(thrift.TType.I32, enums.length));
      for(var elem48 in enums) {
        oprot.writeI32(elem48);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(_A_BOOL_FIELD_FIELD_DESC);
    oprot.writeBool(aBoolField);
    oprot.writeFieldEnd();
    if(this.a_union != null) {
      oprot.writeFieldBegin(_A_UNION_FIELD_DESC);
      a_union.write(oprot);
      oprot.writeFieldEnd();
    }
    if(this.typedefOfTypedef != null) {
      oprot.writeFieldBegin(_TYPEDEF_OF_TYPEDEF_FIELD_DESC);
      oprot.writeString(typedefOfTypedef);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(_DEPR_FIELD_DESC);
    oprot.writeBool(depr);
    oprot.writeFieldEnd();
    if(this.deprBinary != null) {
      oprot.writeFieldBegin(_DEPR_BINARY_FIELD_DESC);
      oprot.writeBinary(deprBinary);
      oprot.writeFieldEnd();
    }
    if(this.deprList != null) {
      oprot.writeFieldBegin(_DEPR_LIST_FIELD_DESC);
      oprot.writeListBegin(new thrift.TList(thrift.TType.BOOL, deprList.length));
      for(var elem49 in deprList) {
        oprot.writeBool(elem49);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  String toString() {
    StringBuffer ret = new StringBuffer("EventWrapper(");

    if(ID != null) {
      ret.write("iD:");
      ret.write(this.iD);
    }

    ret.write(", ");
    ret.write("ev:");
    if(this.ev == null) {
      ret.write("null");
    } else {
      ret.write(this.ev);
    }

    ret.write(", ");
    ret.write("events:");
    if(this.events == null) {
      ret.write("null");
    } else {
      ret.write(this.events);
    }

    ret.write(", ");
    ret.write("events2:");
    if(this.events2 == null) {
      ret.write("null");
    } else {
      ret.write(this.events2);
    }

    ret.write(", ");
    ret.write("eventMap:");
    if(this.eventMap == null) {
      ret.write("null");
    } else {
      ret.write(this.eventMap);
    }

    ret.write(", ");
    ret.write("nums:");
    if(this.nums == null) {
      ret.write("null");
    } else {
      ret.write(this.nums);
    }

    ret.write(", ");
    ret.write("enums:");
    if(this.enums == null) {
      ret.write("null");
    } else {
      ret.write(this.enums);
    }

    ret.write(", ");
    ret.write("aBoolField:");
    ret.write(this.aBoolField);

    ret.write(", ");
    ret.write("a_union:");
    if(this.a_union == null) {
      ret.write("null");
    } else {
      ret.write(this.a_union);
    }

    ret.write(", ");
    ret.write("typedefOfTypedef:");
    if(this.typedefOfTypedef == null) {
      ret.write("null");
    } else {
      ret.write(this.typedefOfTypedef);
    }

    ret.write(", ");
    ret.write("depr:");
    ret.write(this.depr);

    ret.write(", ");
    ret.write("deprBinary:");
    if(this.deprBinary == null) {
      ret.write("null");
    } else {
      ret.write("BINARY");
    }

    ret.write(", ");
    ret.write("deprList:");
    if(this.deprList == null) {
      ret.write("null");
    } else {
      ret.write(this.deprList);
    }

    ret.write(")");

    return ret.toString();
  }

  bool operator ==(Object o) {
    if(o == null || !(o is EventWrapper)) {
      return false;
    }
    EventWrapper other = o as EventWrapper;
    return this.iD == other.iD
      && this.ev == other.ev
      && this.events == other.events
      && this.events2 == other.events2
      && this.eventMap == other.eventMap
      && this.nums == other.nums
      && this.enums == other.enums
      && this.aBoolField == other.aBoolField
      && this.a_union == other.a_union
      && this.typedefOfTypedef == other.typedefOfTypedef
      && this.depr == other.depr
      && this.deprBinary == other.deprBinary
      && this.deprList == other.deprList;
  }

  int get hashCode {
    var value = 17;
    value = (value * 31) ^ iD.hashCode;
    value = (value * 31) ^ ev.hashCode;
    value = (value * 31) ^ events.hashCode;
    value = (value * 31) ^ events2.hashCode;
    value = (value * 31) ^ eventMap.hashCode;
    value = (value * 31) ^ nums.hashCode;
    value = (value * 31) ^ enums.hashCode;
    value = (value * 31) ^ aBoolField.hashCode;
    value = (value * 31) ^ a_union.hashCode;
    value = (value * 31) ^ typedefOfTypedef.hashCode;
    value = (value * 31) ^ depr.hashCode;
    value = (value * 31) ^ deprBinary.hashCode;
    value = (value * 31) ^ deprList.hashCode;
    return value;
  }

  EventWrapper clone({
    int iD: null,
    t_variety.Event ev: null,
    List<t_variety.Event> events: null,
    Set<t_variety.Event> events2: null,
    Map<int, t_variety.Event> eventMap: null,
    List<List<int>> nums: null,
    List<int> enums: null,
    bool aBoolField: null,
    t_variety.TestingUnions a_union: null,
    String typedefOfTypedef: null,
    bool depr: null,
    Uint8List deprBinary: null,
    List<bool> deprList: null,
  }) {
    return new EventWrapper()
      ..iD = iD ?? this.iD
      ..ev = ev ?? this.ev
      ..events = events ?? this.events
      ..events2 = events2 ?? this.events2
      ..eventMap = eventMap ?? this.eventMap
      ..nums = nums ?? this.nums
      ..enums = enums ?? this.enums
      ..aBoolField = aBoolField ?? this.aBoolField
      ..a_union = a_union ?? this.a_union
      ..typedefOfTypedef = typedefOfTypedef ?? this.typedefOfTypedef
      ..depr = depr ?? this.depr
      ..deprBinary = deprBinary ?? this.deprBinary
      ..deprList = deprList ?? this.deprList;
  }

  validate() {
    // check for required fields
    if(ev == null) {
      throw new thrift.TProtocolError(thrift.TProtocolErrorType.INVALID_DATA, "Required field 'ev' was not present in struct EventWrapper");
    }
  }
}
