// Autogenerated by Frugal Compiler (3.4.8)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

// ignore_for_file: unused_import
// ignore_for_file: unused_field
import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart' as thrift;
import 'package:actual_base_dart/actual_base_dart.dart' as t_actual_base_dart;

import 'package:dart2_constant/convert.dart' show utf8;

class ActualBaseDartConstants {
  static const int const_i32_from_base = 582;
}
