// Autogenerated by Frugal Compiler (2.14.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package type_test

import (
	"bytes"
	"fmt"

	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var GoUnusedTypesProtection__ int

type Error struct {
	Resource string `json:"resource"`
	Field    string `json:"field"`
	Code     string `json:"code"`
}
type ErrorResponse struct {
	Message string   `json:"message"`
	Errors  []*Error `json:"errors"`
}

// BaseTypeJSONMapping maps between JSON annotations and Thrift structs.
type BaseTypeJSONMapping struct {
	BoolTest   *bool    `json:"boolTest,omitempty"`
	ByteTest   *int8    `json:"byteTest,omitempty"`
	I16Test    *int16   `json:"i16Test,omitempty"`
	I32Test    *int32   `json:"i32Test,omitempty"`
	I64Test    *int64   `json:"i64Test,omitempty"`
	DoubleTest *float64 `json:"doubleTest,omitempty"`
	BinaryTest []byte   `json:"binaryTest,omitempty"`
	StringTest *string  `json:"stringTest,omitempty"`
}

// ContainerTypeJSONMapping maps between JSON annotations and Thrift structs.
type ContainerTypeJSONMapping struct {
	ListTest []*BaseType          `json:"listTest,omitempty"`
	SetTest  map[*BaseType]bool   `json:"setTest,omitempty"`
	MapTest  map[string]*BaseType `json:"mapTest,omitempty"`
	EnumTest *EnumType            `json:"enumTest,omitempty"`
}
