// Autogenerated by Frugal Compiler (3.4.8)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

// ignore_for_file: unused_import
// ignore_for_file: unused_field
import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart' as thrift;
import 'package:vendor_namespace/vendor_namespace.dart' as t_vendor_namespace;

import 'package:dart2_constant/convert.dart' show utf8;

class VendorNamespaceConstants {
  static const int a_const = 1;
}
