// Autogenerated by Frugal Compiler (3.4.12)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

// ignore_for_file: unused_import
// ignore_for_file: unused_field
import 'dart:convert' show utf8;
import 'dart:typed_data' show Uint8List;

import 'package:thrift/thrift.dart' as thrift;
import 'package:vendor_namespace/vendor_namespace.dart' as t_vendor_namespace;

class VendorNamespaceConstants {
  static const int a_const = 1;
}
